### ISSUE TITLE
Suggest proper name is `prism-element`

### ISSUE THREAD

**Issue by sjmiles** [PolymerElements/prism-element#1]
The `Molecules` product is aimed at containing elements that wrap third-party libraries. The current naming convention for such elements is `<name-of-lib>-element`.

If I've missed some context, my bad.

**Comment by nevir** [comment]
It's a bit weird since this is more about setting up prism as a plugin to `markdown-element`; but this also has `prism-import.html` so I can see both sides!

`prism-element` it is

**Comment by kevinpschaaf** [comment]
Let's make it so!
