### ISSUE TITLE
Can be used as an editor for markdown ?

### ISSUE THREAD

**Issue by joeblew99** [PolymerElements/prism-element#21]
### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

Just wondering if it can be used as an online editor.
I only need to edit markdown documents.

I need to add image upload download also but that would be s different component

**Comment by FredKSchott** [comment]
Sorry, prism is a syntax highlighter and doesn't work as an editor. You can play around with making it [content-editable](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Editable_content), but ultimately this isn't supported.

See http://prismjs.com/ for what prism can and cannot do.
