### ISSUE TITLE
Component not working while in shadowdom mode

### ISSUE THREAD

**Issue by mohanaravind** [PolymerElements/prism-element#22]
### Description

Syntax highlight doesnt work if Polymer is configured to run under shadow dom mode
### Expected outcome

Highlighting must work

### Actual outcome

No code highlight. But the code gets rendered.

### Steps to reproduce

```
  <script>
    /* this script must run before Polymer is imported */
    window.Polymer = {
      dom: 'shadow',
      lazyRegister: true
    };
  </script>
```
### Browsers Affected

- [X] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by notwaldorf** [comment]
You need to import the `prism-default-theme` style: http://jsbin.com/rupoya/edit?html,output

I'll send a PR to update this in the demo.

**Comment by runn-vermel** [comment]
This doesn't work for me - i still don't have highlighting with shadow dom flag="true"
