### ISSUE TITLE
Double Highlight

### ISSUE THREAD

**Issue by mbleigh** [PolymerElements/prism-element#3]
This element is designed to be a "drop in once on the page" affair, but sometimes that's not going to be possible (for example, when a third-party element makes use of it that you're including on your page). Right now, this can cause a double-highlight where the highlight HTML is then highlighted.

I'd propose some kind of mechanism (shouldn't be too hard) that marks a highlight as already having happened and therefore not allowing other listening `prism-highlighter` elements to double up.

**Comment by notwaldorf** [comment]
AJ can you please take a look? Thanks! :balloon:

**Comment by notwaldorf** [comment]
Is there any interest from the community to help with this?

**Comment by 43081j** [comment]
@notwaldorf maybe #18 is enough for this, do take a look if you get chance. thanks!
