### ISSUE TITLE
Not working for Polymer 3

### ISSUE THREAD

**Issue by vrawat79** [PolymerElements/prism-element#45]
Followed the Documentation to use this in a Polymer 3 element but it doesn't work. 
### Description

Following error is shown in Chrome's Console. 
my-view1.js:179 Uncaught TypeError: Cannot assign to read only property 'detail' of object '#<CustomEvent>'
    at HTMLElement.connectedCallback (my-view1.js:179)
    at my-view1.js:190

Basically, in the  connectedCallback() {
    super.connectedCallback();
    var ev = new CustomEvent('syntax-highlight'); // enter code and language here
    ev.detail = {....};

The error suggests that ev.detail is readOnly. 
Also, there is another error that below import is not found. 
import '@polymer/prism-element/prism-element.js';

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by vrawat79** [comment]
This seems to fix the issue. 
const ev = new CustomEvent('syntax-highlight', {detail:{
            code: 'p { background-color: blue }',            
                lang: 'css'}});
But the highlighting still doesn't work.

**Comment by appreciated** [comment]
The last missing bit to make it work is that it is actually not `lang` but the `language` attribute. 
Same is the the element itself. 
For the event only code seems to be needed. 
```
        let ev = new CustomEvent('syntax-highlight', {
            detail: {
                code: this.code
            }
        });
```

**Comment by appreciated** [comment]
Also fiddeling in the `prism-theme-default.js` and the polymer template helped getting the linebreak working.
```
return html`
<style include="prism-theme"></style>
<div id="parent">
    <prism-highlighter></prism-highlighter>
    <pre id="output"></pre>
</div>
`;
```
Additionally replacing `pre[class*="language-"]` with `pre` and `code[class*="language-"]` with `code` in the `prism-theme-default.js` was necessary.
